### ISSUE TITLE
Consider moving freeze_iers to desiutil

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisurvey#106]
`freeze_iers()` currently has *two* purposes:

1. The normal purpose of preventing code on a compute node from being forced to download the IERS-A table.
2. The extra, workaround purpose of preventing *all* code from downloading the IERS-A table from a server that is unavailable.

This creates a dependency on desisurvey for code that would not normally ever need that dependency.  If `freeze_iers()` were moved to desiutil, this extra dependency would be unnecessary.

**Comment by dkirkby** [comment]
There is a third purpose, which was the original motivation and the reason it currently lives in desisurvey: ensure exactly reproducible coordinate transformations over the survey duration for the purpose of scheduling tiles in forecasts and operations.

**Comment by weaverba137** [comment]
Good point, but that would not prevent us from moving the code to desiutil.

**Comment by weaverba137** [comment]
In addition: from recent tests on desisim, it looks like `freeze_iers()` is not compatible with astropy 4.0.  Make sure to test this if/when this moves to desiutil.
