### ISSUE TITLE
new afternoon planning input: tiles eligible to observe

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#17]
Add a new input to afternoon planning: a list of tiles that are eligible to observe.  Only those tiles would be ranked and included in the outputs.

Tiles not on that list don't have fiber assignment finalized yet; see [DESI-2728](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=2728) for background.

**Comment by dkirkby** [comment]
This issue is superseded by the latest updates, where the list of tiles eligible to observe and fiber assign are automatically tracked.
