### ISSUE TITLE
tools for when to rerun fiber assignment

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#18]
Write new tools for determining which tiles are eligible for fiber assignment, i.e. all of the lower pass tiles that cover it have been observed and processed.  Integrate the output of that with the inputs to fiber assignment.  Another output of these tools is the list of tiles eligible for observing used as an input to afternoon planning described in #17 .

See [DESI-2728](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=2728) for a discussion of when fiber assignment should be rerun on what tiles and how that interacts with the survey strategy.

I'm assigning this ticket in desisurvey (not fiberassign) since this is a survey strategy choice, not the choice of fiber assignment itself.

**Comment by sbailey** [comment]
Here is the state machine from [DESI-2728](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=2728) that the tools should help automate to assist the human survey coordinator.  Note that some transitions are automatic, while others could be organized by the tools but the actual state transition is the survey coordinator's choice:

![tilestate](https://cloud.githubusercontent.com/assets/218471/23887445/2108dee0-083f-11e7-9a4e-6b059506ddcb.png)

**Comment by dkirkby** [comment]
Is it useful to keep this issue open?  The state machine above is still valid except that now the right-most two boxes should be updated to reflect the monthly FA cadence.

**Comment by sbailey** [comment]
Internally surveyplan knows which tiles should be fiber assigned, but it doesn't seem to dump that into a list for someone to use for actually doing fiber assignment.  If that does exist, please point me to that.  Or perhaps it is just a matter of needing documentation about the progress.fits file to know how to interpret the "status" column and some tools for parsing that as input for fiber assignment.

Related: We also appear to be missing the hooks for doing the human overrides to force or avoid observation.  These should be separate files with just the overrides, not a human hand-editing the standard FITS file output to replace the automated progress report.
