### ISSUE TITLE
move desisurvey.nightops to surveysim

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#22]
`desisurvey.nightopts` is simulating the nightly operations, and thus should be moved to surveysim.  desisurvey should be reserved for code like afternoon planning and the next field selector that will get used in real operations.

Since several people are working on desisurvey / surveysim right now, assign this ticket to yourself when you start working on it so that others won't do the same refactor at the same time, then fix it and submit a PR quickly.

**Comment by sbailey** [comment]
Head's up: I'm claiming this issue and moving nightops to desisim now, with a PR including it coming later this afternoon.

**Comment by dkirkby** [comment]
The second part of this, removing nightops from this package, was completed in #30.
