### ISSUE TITLE
add .travis.yml

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#37]
Add .travis.yml to run tests automatically

**Comment by dkirkby** [comment]
I can get a start on this if @weaverba137 can point me to a `best practices` example to start from (presumably not the astropy flavor that I am used to).

**Comment by weaverba137** [comment]
Depends.  If desisurvey has many external package dependencies (astropy stack, matplotlib, etc.), you should use desispec as a template.  If desisurvey has very few external dependencies, then desiutil is a good template.  I actually need to upgrade the desitemplate product to reflect the latest changes I've made to desiutil.

**Comment by dkirkby** [comment]
Here are the `requirements.txt`:
```
setuptools
numpy
scipy
astropy
pyephem
pytz
```

**Comment by weaverba137** [comment]
Definitely use desispec as a template then.

**Comment by dkirkby** [comment]
I have not any progress here (and still have no travis expertise).

@weaverba137 Do you have time to add a .travis file to this repo?

All tests *should* pass once #60 is merged.

**Comment by weaverba137** [comment]
I'm observing at Kitt Peak, but I can take a look sometime this week.

**Comment by weaverba137** [comment]
@dkirkby, in addition to the external packages already mentioned, does desisurvey depend on any DESI packages, besides desiutil?

**Comment by weaverba137** [comment]
OK, definitely needs specsim.

**Comment by weaverba137** [comment]
While running tests, I noticed that several of the tests require downloading external data sets.  This is not good practice for Travis tests.  If necessary, you can cache these data sets in the tests directory of the package.

**Comment by weaverba137** [comment]
While running tests, I found these additional packages were necessary:

* healpy
* specsim
* speclite
* desimodel

While running tests on my own machine, I found the following additional error:

```

======================================================================
ERROR: test_ctor (desisurvey.test.test_progress.TestProgress)
Create a new table from scratch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/weaver/Documents/Code/git/desihub/desisurvey/py/desisurvey/test/test_progress.py", line 41, in test_ctor
    self.assertEqual(type(p.get_tile(10)), astropy.table.Row)
  File "/Users/weaver/Documents/Code/git/desihub/desisurvey/py/desisurvey/progress.py", line 289, in get_tile
    raise ValueError('Invalid tile_id {0}.'.format(tile_id))
ValueError: Invalid tile_id 10.
```
Not sure how 10 could possibly invalid here.
