### ISSUE TITLE
surveyplan start/stop options

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#50]
Add options to `surveyplan` to specify the start/stop dates of the plan.  These should be arbitrary, i.e. could be outside of the bounds of the nominal 5-year DESI survey defined in the config file.

I think it probably would be ok to raise an error if the requested dates are not a subset of the dates used for the initial `surveyplan --create ...` call (which itself should allow specifying start/stop dates).  Alternatively, that could trigger an update of the `scheduler.fits` file to include the new dates.

**Comment by dkirkby** [comment]
Surveyplan is now called each afternoon, and `surveysim` already supports the necessary start/stop options to simulated a limited date range.
