### ISSUE TITLE
finalize afternoon planning operations

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#70]
Finalize the details of how afternoon planning will be run during operations and write any necessary wrapper code.  Example issues to sort out (probably not a complete list):

* Will this be a cronjob or triggered by ICS?  If a cronjob, how will it handle the changing time of sunset?
* How will it get offline data back from NERSC?  rsync?  wget?  git?  Exactly what data does it need and from what offline files will it get that?
* How will history be preserved?  e.g. will the nightly plan be checked into svn or git, or included in the nightly dataflow for archive?
* What planning QA will be generated each night?  Will these be static files or ingested into QLF?
* Currently `surveyplan` uses progress.fits to know what was observed or not.  How will it get that information in real operations?  How will it handle discrepancies between what ETC/ICS thought and the offline pipeline though for S/N and overall tile quality?

**Comment by schlafly** [comment]
We've been running afternoon planning for a while.  Answering the bullets above:
- these are presently run manually.  We may migrate to LO.
- we're wgetting from NERSC.  We rely on offline pipeline assessments of tile and exposure completeness.
- we leave directories with AP state each night lying around, though these should be better organized.   They are not archived or checked in anywhere, and it's not clear we want them to be, though important bits of them are (e.g., surveyops tile file).
- We're not currently generating nightly QA beyond "backup plans" that are posted to the wiki.  Some visualization of these would be appropriate, as well as nightly completeness plots, etc., though things like desidash also cover some of this terrain.
- Information in real operations comes from the raw data stream, the ETC, and the offline pipeline completeness estimates.
