### ISSUE TITLE
Need code to generate fibermap files

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#71]
Write code to combine next field selector output plus fiber view camera data into fibermap files.

Filing under desisurvey since this is code that will run at the mountain as part of operations to generate the fibermap files to be included in the datastream alongside the spectrograph raw data.  The actual code may live somewhere under ICS.

Note: the [fibermap format](http://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_DATA/NIGHT/fibermap-EXPID.html) is very fundamental to the spectro pipeline operations, but it also needs to be updated to synchronize with upstream information from target selection and fiber assignment.

**Comment by schlafly** [comment]
Closing this as it's done and it's no longer seen as a desisurvey feature.
