### ISSUE TITLE
finalize NFS file format interface with ICS

### ISSUE THREAD

**Issue by sbailey** [desihub/desisurvey#72]
Related to #24 (update next field selector interface) and desihub/desitarget#232 (GFA targets)

Finalize the file format for how next field selector information is passed to ICS.  This file should include everything needed to request an exposure, e.g. so that a year later one could re-use the same file to request another observation of a calibration field.  Similarly, a test or commissioning program should be able to write a file of this format and use it to request an exposure, completely independently from the NFS.

This might just be an update to the fiber assignment file format, or it might require merging in other sources of data.  To do:
* sort out the details
* document it
* update the current NFS selector and/or fiberassignment code so that it writes that format
* make sure ICS agrees that this interface is sufficient

### Notes 

Originally we had defined the NFS -> ICS interface as a function call returning a data structure defining the observation request.  We still wanted to archive the state of that request in a file, and later moved to the file itself being the interface.

The current fiber assignment format is not yet sufficient, at minimum because it doesn't include GFA targets or proper motion data.  Sorting out the NFS -> ICS interface may identify other missing pieces.

Exception to the "everything needed to define an exposure" requirement?  We had discussed including the expected exposure time, which depends upon current conditions.  I think this is only informational and is not *required* to be able to take an exposure.  Is there anything else that we want to include in NFS -> ICS that couldn't be calculated well in advance?

**Comment by schlafly** [comment]
We have a working ICS interface.  A fiberassign file includes everything needed to make an observation, though other keywords are used to specify exposure time / ETC desired EFFTIME.
